CD Testing

diff --git a/.github/workflows/packerbuild.yml b/.github/workflows/packerbuild.yml
--- a/.github/workflows/packerbuild.yml
+++ b/.github/workflows/packerbuild.yml
@@ -84,16 +84,26 @@ jobs:
         run: packer init -upgrade packer/
 
       - name: Build Custom Image
+        id: build-ami
         run: |
           AMI_ID=$(packer build \
             -var "aws_region=${{ secrets.AWS_REGION }}" \
             -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
             -var "instance_type=t2.micro" \
             -var "ami_users=[\"${{ secrets.AMI_USERS }}\"]" \
-            packer/ | grep -oP '(?<=AMI: ).*')
+            packer/ | grep -o 'ami-[0-9a-f]\{17\}')
+          if [ -z "$AMI_ID" ]; then
+            echo "Error: Failed to extract AMI ID from Packer output."
+            exit 1
+          fi
+          echo "AMI ID: $AMI_ID"
           echo "ami-id=$AMI_ID" >> $GITHUB_OUTPUT
         env:
           PACKER_LOG: 1
+
+      - name: Debug AMI ID
+        run: |
+          echo "AMI ID from build-ami: ${{ steps.build-ami.outputs.ami-id }}"
             
       # - name: Copy GCP Image to Demo Project
       #   env:
